version: 2.1

jobs:
  build_dev:
    working_directory: ~/logs
    docker:
      - image: cimg/base:2022.09
    environment:
      DOCKER_VERSION: default
      BUILD_PATH: /tmp/container-build
      CONTAINER_NAME: apache
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build DEV Apache Docker Image
          command: |
            cp .env.example .env
            echo "NODE_ENVIRONMENT=dev" >> .env
            make build
      - run:
          name: Start DEV Container
          command: |
            set -x
            ls -la
            pwd
            make run
            docker ps -a
            sleep 10
      - run:
          name: Global Environment Vars
          command: |
            docker exec ${CONTAINER_NAME} /bin/bash -c "export"
      - run:
          name: DEV Build Tests
          command: |
            docker exec ${CONTAINER_NAME} /bin/bash /opt/tests/build_tests.sh
      - run:
          name: Collect DEV Container Logs
          command: |
            mkdir -p ${BUILD_PATH}
            docker logs ${CONTAINER_NAME} > ${BUILD_PATH}/log_output-DEV_Apache.txt
            docker logs db > ${BUILD_PATH}/log_output-DEV_MySQL.txt
      - run:
          name: Kill DEV Containers
          command: |
            make stop
      - store_artifacts:
          path: /tmp/container-build
          destination: build-logs-dev

  build_production:
    working_directory: ~/logs
    docker:
      - image: cimg/base:2022.09
    environment:
      DOCKER_VERSION: default
      BUILD_PATH: /tmp/container-build
      CONTAINER_NAME: apache
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Production Apache Docker Image
          command: |
            cp .env.example .env
            echo "NODE_ENVIRONMENT=production" >> .env
            make build
      - run:
          name: Start Production Container
          command: |
            set -x
            ls -la
            pwd
            make run
            docker ps -a
            sleep 10
      - run:
          name: Global Environment Vars
          command: |
            docker exec ${CONTAINER_NAME}-web-1 /bin/bash -c "export"
      - run:
          name: Production Build Tests
          command: |
            docker exec ${CONTAINER_NAME}-web-1 /bin/bash /opt/tests/build_tests.sh
      - run:
          name: Collect Production Container Logs
          command: |
            mkdir -p ${BUILD_PATH}
            docker logs ${CONTAINER_NAME}-web-1 > ${BUILD_PATH}/log_output-LIVE_Apache.txt
            docker logs ${CONTAINER_NAME}-db-1 > ${BUILD_PATH}/log_output-LIVE_MySQL.txt
      - run:
          name: Kill Production Containers
          command: |
            make stop
      - store_artifacts:
          path: /tmp/container-build
          destination: build-logs-production

workflows:
  build_and_test:
    jobs:
      - build_dev
      - build_production