version: 2.1

jobs:
  build_dev:
    working_directory: ~/project
    docker:
      - image: docker:20.10
    resource_class: arm.medium
    environment:
      DOCKER_VERSION: 20.10
      BUILD_PATH: ~/container-build
      CONTAINER_NAME: apache
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10
      - run:
          name: Install Build Tools
          command: apk add --no-cache make bash curl git
      - run:
          name: Build DEV Apache Docker Image
          command: |
            cp .env.example .env
            echo "NODE_ENVIRONMENT=dev" >> .env
            echo "BUILD_ENV=dev" >> .env
            echo "SMTP_HOST=smtp.example.com" >> .env
            echo "SASL_USER=your_smtp_user" >> .env
            echo "SASL_PASS=your_smtp_pass" >> .env
            echo "LOG_TOKEN=your_log_token" >> .env
            make build
      - run:
          name: Start DEV Container
          command: |
            set -x
            pwd
            ls -la
            ls -la ~/project/tests
            make run
            docker ps -a
            sleep 2
      - run:
          name: Global Environment Vars
          command: |
            docker exec ${CONTAINER_NAME} /bin/bash -c "export"
      - run:
          name: DEV Build Tests
          command: |
            docker exec ${CONTAINER_NAME} /bin/bash /opt/tests/build_tests.sh # Docker container file system
      - run:
          name: Collect DEV Container Logs
          command: |
            mkdir -p ${BUILD_PATH}
            docker logs ${CONTAINER_NAME} > ${BUILD_PATH}/log_output-DEV_Apache.txt
            docker logs apache-db-1 > ${BUILD_PATH}/log_output-DEV_MySQL.txt
      - run:
          name: Kill DEV Containers
          command: |
            make stop
      - store_artifacts:
          path: /tmp/container-build
          destination: build-logs-dev

  build_production:
    working_directory: ~/project
    docker:
      - image: docker:20.10
    resource_class: arm.medium
    environment:
      DOCKER_VERSION: 20.10
      BUILD_PATH:  ~/project/container-build
      CONTAINER_NAME: apache
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10
      - run:
          name: Install Build Tools
          command: apk add --no-cache make bash curl git
      - run:
          name: Build Production Apache Docker Image
          command: |
            cp .env.example .env
            echo "NODE_ENVIRONMENT=production" >> .env
            echo "BUILD_ENV=production" >> .env
            echo "SMTP_HOST=smtp.example.com" >> .env
            echo "SASL_USER=your_smtp_user" >> .env
            echo "SASL_PASS=your_smtp_pass" >> .env
            echo "LOG_TOKEN=your_log_token" >> .env
            make build
      - run:
          name: Start Production Container
          command: |
            set -x
            pwd
            ls -la
            ls -la ~/project/tests
            make run
            docker ps -a
            sleep 2
      - run:
          name: Global Environment Vars
          command: |
            docker exec ${CONTAINER_NAME} /bin/bash -c "export"
      - run:
          name: Production Build Tests
          command: |
            docker exec ${CONTAINER_NAME} /bin/bash /opt/tests/build_tests.sh # Docker container file system
      - run:
          name: Collect Production Container Logs
          command: |
            mkdir -p ${BUILD_PATH}
            docker logs ${CONTAINER_NAME} > ${BUILD_PATH}/log_output-LIVE_Apache.txt
            docker logs apache-db-1 > ${BUILD_PATH}/log_output-LIVE_MySQL.txt
      - run:
          name: Kill Production Containers
          command: |
            make stop
      - store_artifacts:
          path: ~/project/container-build
          destination: build-logs-production

workflows:
  build_and_test:
    jobs:
      - build_dev
      - build_production
