# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

settings = YAML.load_file 'vagrant.yml'
token 	= settings['api']['token'] # It's called "personal access token" on the site
box_name = settings['api']['web']['name'] # If the key is already on your account, this name must match or it will error when trying to re-add
host 	= settings['api']['local']['host']
guest 	= settings['api']['local']['guest']


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.define :hgWeb do |web_config|

		web_config.vm.box = "digital_ocean"
		web_config.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
		web_config.vm.synced_folder ".", "/vagrant", disabled: true
	  	web_config.ssh.private_key_path = '.ssh/id_rsa' # Easy to use your existing key, will be added to DO
	  	web_config.ssh.username = 'htmlgraphic'

		web_config.vm.provider :digital_ocean do |do_config|
			do_config.token = token
			do_config.ssh_key_name = box_name 
			do_config.image = 'Ubuntu 14.04 x64'
			do_config.size = '512mb'
			do_config.region = 'nyc2'
		end
	end

	config.vm.define :dev do |vb_config|
		vb_config.vm.box = "ubuntu/trusty64"
		vb_config.vm.synced_folder host, guest, disabled: false
		vb_config.vm.network :private_network, ip: "33.33.33.10"
		vb_config.vm.network :forwarded_port, guest: 80, host: 8080
	end

end
