require 'yaml'

configValues = YAML.load_file 'vagrant.yaml'
data = configValues['vagrantfile-digital_ocean']

host  = data['vm']['local']['host']
guest = data['vm']['local']['guest']


Vagrant.require_version '>= 1.6.0'

Vagrant.configure('2') do |config|

	config.vm.define data['vm']['hostname'] do |web_config|

		web_config.vm.box 		= "digital_ocean"
		web_config.vm.hostname 	= data['vm']['hostname']

		web_config.vm.box_url 	= "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
		web_config.vm.synced_folder ".", "/vagrant", disabled: true
	  	web_config.ssh.private_key_path = data['vm']['ssh']['private_key_path'] # Easy to use your existing key, will be added to DO
	  	web_config.ssh.username = data['vm']['ssh']['username']

		web_config.vm.provider :digital_ocean do |do_config|
			do_config.ssh_key_name = data['vm']['provider']['digital_ocean']['ssh_key_name']
			do_config.token 	   = data['vm']['provider']['digital_ocean']['token']
			do_config.image        = data['vm']['provider']['digital_ocean']['image']
    		do_config.region       = data['vm']['provider']['digital_ocean']['region']
    		do_config.size         = data['vm']['provider']['digital_ocean']['size']
		end
	end

	config.vm.define :dev do |vb_config|
		vb_config.vm.box = "ubuntu/trusty64"
		vb_config.vm.synced_folder host, guest, disabled: false
		vb_config.vm.network :private_network, ip: "33.33.33.10"
		vb_config.vm.network :forwarded_port, guest: 80, host: 8080
	end

end
